language: node_js

os:
    - linux
    - osx

node_js:
    - node
    - iojs
    - lts/*
    - 8
    - 7
    - 6
    - 5
    - 4

before_script:
    - npm install

script:
    - npm run testdox

notifications:
    email: false
